#!/usr/bin/env node
/**
 * Bundle every dsh client half under packages/web/<name>/src/client
 * into the repo-root dist/plugins/<name>/client.js (alongside tsc server output).
 *
 * Delivery shape: window.__ModuleLoader__.load({ id, factory(require){...} }).
 * CSS imports become string defaults (inlined into a style[data-plugin-css] at runtime).
 *
 * package.json exports["./client"] must resolve to that dist path so dsh-client-modules
 * can serve /plugins/<id>/client.js from the file: package root.
 */
import { existsSync } from "node:fs";
import { mkdir, readFile, readdir } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PLUGINS = join(ROOT, "packages", "web");
const DIST_PLUGINS = join(ROOT, "dist", "plugins");
const CORE = join(ROOT, "packages", "core");

/** Frozen module table seeds — must stay external (browser require). */
const PLATFORM_EXTERNALS = [
  "react",
  "react/jsx-runtime",
  "react-dom",
  "react-dom/client",
  "@deepseek-ai/cordis",
  "@deepseek-ai/dsh-client-ui-slots",
  "@deepseek-ai/dsh-client-web-react",
  "@deepseek-ai/dsh-client-ui-primitives",
  "@deepseek-ai/dsh-client-ui-attachment",
  "@deepseek-ai/dsh-client-schema-form",
];

/** Bundled into the plugin factory — not a dsh platform seed. */
const BUNDLED_BARE = /^(?:three|three\/)/;

function laresCorePlugin() {
  return {
    name: "lares-core",
    setup(build) {
      build.onResolve({ filter: /^@olares\/lares-core\// }, (args) => {
        const subpath = args.path.slice("@olares/lares-core/".length);
        return { path: join(CORE, `${subpath}.js`) };
      });
    },
  };
}

function platformExternalsPlugin() {
  const allowed = new Set(PLATFORM_EXTERNALS);
  return {
    name: "dsh-platform-externals",
    setup(build) {
      build.onResolve({ filter: /^[^./]|^@/ }, (args) => {
        if (args.path.startsWith("@olares/lares-core/")) return;
        if (allowed.has(args.path)) return { path: args.path, external: true };
        if (BUNDLED_BARE.test(args.path)) return;
        return {
          errors: [
            {
              text: `Unsupported bare client import ${JSON.stringify(args.path)}; use a relative source import, @olares/lares-core/*, or a dsh platform seed`,
            },
          ],
        };
      });
    },
  };
}

function cssTextPlugin() {
  return {
    name: "lares-css-text",
    setup(build) {
      build.onLoad({ filter: /\.css$/ }, async (args) => {
        const raw = await readFile(args.path, "utf8");
        const text = raw.replace(/\r\n/g, "\n").trim();
        return { contents: `export default ${JSON.stringify(text)};\n`, loader: "js" };
      });
    },
  };
}

function resolveExportClient(pkgDir, pkg) {
  const client = pkg.exports?.["./client"];
  if (typeof client === "string") return resolve(pkgDir, client);
  if (client && typeof client === "object" && typeof client.default === "string") {
    return resolve(pkgDir, client.default);
  }
  return null;
}

async function discoverTargets() {
  const names = await readdir(PLUGINS);
  const targets = [];
  for (const name of names) {
    const pkgDir = join(PLUGINS, name);
    const pkgPath = join(pkgDir, "package.json");
    if (!existsSync(pkgPath)) continue;
    const pkg = JSON.parse(await readFile(pkgPath, "utf8"));
    if (!pkg.dsh?.client) continue;
    const src = join(pkgDir, "src", "client", "index.js");
    if (!existsSync(src)) {
      throw new Error(`${pkg.name}: declares dsh.client but has no src/client/index.js`);
    }
    const outfile = join(DIST_PLUGINS, name, "client.js");
    const declared = resolveExportClient(pkgDir, pkg);
    if (!declared) {
      throw new Error(`${pkg.name}: declares dsh.client + src/client but exports["./client"] is missing`);
    }
    if (declared !== outfile) {
      throw new Error(
        `${pkg.name}: exports["./client"] must resolve to ${relative(ROOT, outfile)} (got ${relative(ROOT, declared)})`,
      );
    }
    targets.push({ id: pkg.name, name, pkgDir, src, outfile });
  }
  return targets;
}

function wrapper(id) {
  const banner = [
    `// GENERATED by scripts/build-client.mjs — do not edit.`,
    `window.__ModuleLoader__.load({`,
    `  id: ${JSON.stringify(id)},`,
    `  factory: (require) => {`,
    `    var module = { exports: {} };`,
    `    var exports = module.exports;`,
  ].join("\n");
  const footer = [
    `    return module.exports;`,
    `  },`,
    `});`,
    ``,
  ].join("\n");
  return { banner, footer };
}

async function buildOne(target) {
  const { banner, footer } = wrapper(target.id);
  await mkdir(dirname(target.outfile), { recursive: true });
  await esbuild.build({
    absWorkingDir: ROOT,
    entryPoints: [target.src],
    outfile: target.outfile,
    bundle: true,
    format: "cjs",
    platform: "browser",
    target: ["es2020"],
    logLevel: "silent",
    plugins: [laresCorePlugin(), platformExternalsPlugin(), cssTextPlugin()],
    minify: false,
    legalComments: "none",
    sourcemap: true,
    banner: { js: banner },
    footer: { js: footer },
  });
  console.log(`  ${target.id} → ${relative(ROOT, target.outfile)}`);
}

const targets = await discoverTargets();
if (targets.length === 0) {
  console.log("build-client: no packages/web/*/src/client/index.js targets");
  process.exit(0);
}

console.log(`build-client: ${targets.length} plugin(s) → dist/plugins/`);
await Promise.all(targets.map(buildOne));
